name: Nyctophobia
version: 1.12
main: dev.timecoding.nyctophobia.Nyctophobia
api-version: 1.18
authors: [ TimeCoding ]
description: Let the players feel fear!
website: timecoding.de

commands:
  nyc:
    aliases: nyctophobia
    description: The MainCommand for the Plugin Nyctophobia!
